swagger: "2.0.0"
info:
  title: MEAN Stack API Documentation
  summary: Official API Documentation for Posist Technologies
  description: APi Documentation for Posist Technologies
  version: 1.0.0
  contact:
    email: choudharysidharth082000@gmail.com
  servers:
    - url: "http://localhost:3000"
      description: "Local Server Running"
    - url: "https://testcyberflow.herokuapp.com"
      description: "Main Server"

schemes: [http, https]

paths:
  /v1/testApi:
    get:
      tags:
        - Test
      summary: Test Api
      description: Return HEllo world
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/testAPI/checkUserLogin:
    get:
      tags:
        - Session
      summary: Test Api
      description: Return HEllo world
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/session/checkUserLogin:
    get:
      tags:
        - Session
      summary: Check Session Data
      description: Checking the user session in the server
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/brand/createBrand/{userID}:
    post:
      tags:
        - Brand
      summary: Create Brand
      description: Create a new brand
      parameters:
        - in: path
          type: string
          required: true
          name: userID
        - in: body
          name: brandBody
          schema:
            type: object
            properties:
              brandName:
                type: string
              brandDescription:
                type: string
              brandLogo:
                type: string
              brandWebsite:
                type: string
              brandEmail:
                schema: 
                  type: array
                properties:
                  email:
                    type: string
              brandPhoneNumber:
                type: array
              brandWebsite: 
                type: string
              brandSocialMedia:
                type: array              
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/brand/disableBrand/{brandID}:
    put:
      tags:
        - Brand
      summary: Disable Brand
      description: Disable a brand
      parameters:
        - in: path
          type: string
          required: true
          name: brandID
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error


  /v1/api/user/allUsers:
    get:
      tags:
        - User
      summary: Get All Users
      description: Get all the users from the database
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/user/userById/{id}:
    get:
      tags:
        - User
      summary: Get User By Id
      description: Get the user by id
      parameters:
        - in: path
          name: id
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/user/usersJoinedLastWeek/:
    get:
      tags:
        - User
      summary: Get Users Joined Last Week
      description: Get the users who joined last week
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/user/usersJoinedLastMonth/:
    get:
      tags:
        - User
      summary: Get Users Joined Last Month
      description: Get the users who joined last month
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/getAllDeleted:
    get:
      tags:
        - Admin
      summary: Get All Deleted Users
      description: Get all the deleted users from the database
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/getUsers:
    get:
      tags:
        - Admin
      summary: Get All Users
      description: Get all the users from the database
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/getUsers/{id}:
    get:
      tags: 
        - Admin
      summary: Get User By Id
      description: Get the user by id
      parameters:
        - in: path
          name: id
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login to the system
      parameters:
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/auth/deleteUser/{id}:
    delete:
      tags:
        - Auth
      summary: Delete User
      description: Delete user Permanentnly from the database (Can only be done by the admin)
      parameters:
        - in: path
          type: string
          name: id
          required: true
      responses:
        200:
          description: OK
  /v1/api/outlet/createOutlet/{brandID}/{managerID}:
    post:
      tags: 
        - Outlet
      summary: Create Outlet
      description: Create an outlet for a brand
      parameters: 
        - in: path
          name: brandID
          type: string
          required: true
        - in: path
          name: managerID
          type: string
          required: true
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              outletName:
                type: string
              outletAddress:
                type: string
              outletEmail:
                type: string
              outletWebsite:
                type: string
              outletLogo:
                type: string
              outletDescription:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/foodData/createSuperCategory/{brandID}/{brandName}:
    post:
      tags: 
        - FoodData
      summary: Create the Super Category
      description: Create the super category for the food data
      # security Header Bear Token
      parameters:
        - in: path
          name: brandID
          type: string
          required: true
        - in: path
          name: brandName
          type: string
          required: true
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              superCategoryName:
                type: string
              superCategoryDescription:
                type: string
              superCategoryImage:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
      


      

  /v1/api/auth/updateUser/{id}:
    put:
      tags:
        - Auth
      summary: Update User
      description: Updating the user (can be done by all the users and admin)
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              nameUser:
                type: string
              email:
                type: string
              userName:
                type: string
              mobileNumber:
                type: string
              userType:
                type: string
      responses:
        200:
          description: OK
  /v1/api/brand/getBrands:
    get:
      tags:
        - Brand
      summary: Get All Brands
      description: Get all the brands from the database
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/brand/getBrand/{brandID}:
    get:
      tags:
        - Brand
      summary: Get Brand By Id
      description: Get the brand by id
      parameters:
        - in: path
          name: brandID
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/brand/getDisabledBrands:
    get:
      tags:
        - Brand
      summary: Get All Disabled Brands
      description: Get all the disabled brands from the database
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/brand/enableBrand/{brandID}:
    put:
      tags:
        - Brand
      summary: Enable the Brand
      descruption: Enable the brand (can be done by all the users and admin)
      parameters:
        - in: path
          name: brandID
          type: string
          required: true
      responses:
        200:
          description: OK
  /v1/api/brand/getDeletedBrands:
    get:
      tags:
        - Brand
      summary: Get All Deleted Brands
      description: Get all the deleted brands from the database
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
  /v1/api/brand/updateBrand/{brandID}:
    put:
      tags: 
        - Brand
      summary: Update Brand
      description: Updating the brand (can be done by all the users and admin)
      parameters:
        - in: path
          name: brandID
          type: string
          required: true
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              brandName:
                type: string
              brandLogo:
                type: string
              brandAddress:
                type: array
                items:
                  type: string
              brandDescription:
                type: string
              brandWebsite:
                type: string
              brandSocialMedia:
                type: array
                items:
                  type: object
                  peoperties:
                    socialMediaName:
                      type: string
                    socialMediaLink:
                      type: string
                
      responses:
        200:
          description: OK
          
    

          
              
  /v1/api/auth/signup/{brandID}/{outletID}:
    post:
      tags:
        - Auth
      summary: Signup
      description: Signup to the system
      parameters:
        - in: path
          type: string
          name: brandID
          required: false
        - in: path
          type: string
          name: outletID
          required: false
        - in: body
          name: authBody
          schema:
            type: object
            properties:
              nameUser:
                type: string
              email:
                type: string
              password:
                type: string
              confirmPassword:
                type: string
              usertype:
                type: string
              mobileNumber:
                type: string
              userName:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        400:
          description: Undocumented
        500:
          description: Internal Server Error
